baseURL = "https://katieandtanner.netlify.app/"
languageCode = "en-us"
title = "Katie and Tanner's Blog"
theme = "dream"

defaultContentLanguage = "en"

[params]
	author = "Tanner and Kaite"
	email = "tfolkman33@gmail.com"
	motto = "Hey! Under wedding-updates below you can click the little black arrow to see the posts that we have made so far with the most up to date announcments for our wedding!! Clicking on the Facebook logo will take you to the Facebook event which will also be updated as we get more information!"
	facebook = "events/679094296237426/" 
